### ISSUE TITLE
"Arguments too long" error when including a large number of files

### ISSUE THREAD

**Issue by zst123** [Infineon/core-make#1] opened 2021-10-21 02:15 UTC
**Prerequisites**

Can you reproduce the problem reliably?
> Yes

Did you check current release notes for known issues?
> Not found in release notes

If this is not the latest release, have you checked newer releases? 
> Using version 1.8.0

**Description**:

When placing a folder with a large number of tiles, inside the project sources directory, the Makefile will iterate through all the sub-directories in the include path as well (this is what we want).

Unfortunately, this results in the following error "Argument list too long". The problem is caused due to build.mk (Found in ~/ModusToolbox/workspace/mtb_shared/core-make/release-v1.8.0/make/core/build.mk). To include all the dependencies, all the filenames are echoed into a rpt (report) file using command line parameters. Because there is a maximum limit for bash command line parameters, the process will fail if there are too many files included.

A possible fix will be to use the Makefile $file directive. The $file function is for the Makefile to write values directly to a file. With this, we do not depend on bash parameter expansion and thus do not have the issue of having too many arguments

See my github commit for possible fix
 > https://github.com/zst123/Element14_Low-Power-IoT/commit/f7e30b41c3e962c2d41a1b9b5be77976c9bfd499

**Steps to Reproduce:**

1. Add many files into the "sources" directory

2. Compile and see the error

 - Image of the error: https://www.element14.com/community/servlet/JiveServlet/showImage/38-38593-1092618/fix0.png

**Expected Result:**

Project compiles successfully

**Actual Result:**

Project fails to compile with "Arguments too long" error

**Frequency (1/1, 1/50, 1/100):**

Always happens

**Build/Commit:**

v1.8.0

**Target:**

- PSoC 6 WiFi-BT Pioneer Kit (CY8CKIT-062-WiFi-BT).

**Host OS and Version:**

Linux / Ubuntu 20.04.02 LTS

**Compiler:**

ModusToolbox version 2.3

**Environment**

More information of project is documented on my Element14 project page.

> https://www.element14.com/community/community/design-challenges/low-power-iot/blog/2021/10/21/wearable-gesture-control-5-deploying-edge-impulse-model-fixing-a-makefile-issue

**Comment by AlenAn14** [comment] 2021-12-14 17:00
Hi @zst123 ,

I have raised an internal ticket for this bug and the same is expected to be resolved with the next release i.e. core-make version 2.0.
Thank you for pointing out the same.

Warm Regards
Alen

**Closed as completed** 2021-12-17 16:57 UTC

**Comment by tomoveu** [comment] 2022-03-01 22:06
@AlenAn14 when could we expect the release of core-make version 2.0?

**Comment by AlenAn14** [comment] 2022-08-26 14:03
Hi @tomoveu ,

This fix will be available in the core-make version 3.0.0.

Regards
Alen

**Comment by tomoveu** [comment] 2022-08-29 05:44
@AlenAn14 The current version of core-make is 1.9.1.    When would 3.0.0 come out?

**Comment by AlenAn14** [comment] 2022-09-01 04:20
Hi @tomoveu ,

The version 3.0 of core-make is expected to come out in September of 2022.

Warm Regards
Alen

**Comment by AlenAn14** [comment] 2022-09-13 08:47
Hi @tomoveu ,
Can you please let me know if this issue has been resolved?
I tried cloning the project [here](https://github.com/zst123/Element14_Low-Power-IoT), and running it in ModusToolbox with core-make 1.9.1 and and not observing this error.
I tried 1.8.0 as well and still did not observe this error.
Have you made any changes in the code ? Can you please verify on this once.

**Comment by tomoveu** [comment] 2022-09-13 11:34
@AlenAn14 I am a bit confused by the versioning. Are we now at core-make version 3.0 or 1.9.1? 😃 

I'd be happy to test. This issue can be found on multiple threads in the Infineon forum with 1.8.0

**Comment by AlenAn14** [comment] 2022-09-13 11:37
I was using 1.9.1 with MTB2.4 today and then cloned your project into it, but the error is now not visible. Instead it build successfully.
I also tried using 1.8.0, but was not able to reproduce the error.

**Comment by tomoveu** [comment] 2022-09-13 11:50
@AlenAn14 I don't know about @zst123's project, but I believe he has also hardcoded the fix in his project when using 1.8.0. At least, this was the only fix we could come up - Add PREBUILD command in the Makefile.

**Comment by AlenAn14** [comment] 2022-09-13 11:52
What should I assign/the command to the PREBUILD flag?

I also tried creating multiple folders recursively in the project and put a required source file in the innermost folder.
It was still able to get the .c file without throwing this error.

I tried in both Windows and Linux and with version 2.3 and 2.4 of MTB.
Still not able to reproduce the issue.

**Comment by tomoveu** [comment] 2022-09-13 14:02
@AlenAn14  sorry for the confusion, the fix is hardcoded in the `build.mk` of core-make like show here

[mtb_shared/core-make/release-v1.8.0/make/core/build.mk](https://github.com/zst123/Element14_Low-Power-IoT/commit/f7e30b41c3e962c2d41a1b9b5be77976c9bfd499#diff-18ef9849f6fe763eed1075a723b0f3304df30f630eae660c83d98cb2aaa5c5e2)

I am **not** familiar with the @zst123 project. We are using core-make v1.9.0 and the issue exists.

**Comment by AlenAn14** [comment] 2022-09-13 16:53
Hi @tomoveu ,
I have cloned the mtb_shared folder newly, so I do not have the fix in my build.mk file of core make.
It is building successfully.
Will it be possible for you to create a sample project that throws this error and share the same with me?
Please share the mtb_shared folder used as well

**Comment by tomoveu** [comment] 2022-12-19 15:55
@AlenAn14 the issue is with long paths, for example:

`/Users/dimitomov/work/mtb-example-edgeimpulse-keyword-spotting/build/APP_CY8CKIT-062-BLE/Debug/ei-model/edge-impulse-sdk/tensorflow/lite/core/api/tensor_utils.cc`

I just tried with Modus Toolbox 3.0 and the issue seems to persist. 

What are you building to test?
